unstable_features = true

brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 100
fn_params_layout = "Compressed"
format_strings = true
group_imports = "StdExternalCrate"
indent_style = "Visual"
imports_granularity = "Module"
max_width = 100
use_small_heuristics = "Max"
